version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - echo "Building with CCP URL = $REACT_APP_CCP_URL"
        - npm run build
        - echo "Listing build/"
        - ls -la build/
        - echo "Listing build/static/"
        - ls -la build/static/
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
