version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd amplify-app
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: amplify-app/build
    files:
      - '**/*'
  cache:
    paths:
      - amplify-app/node_modules/**/*
