version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd custom-ccp
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: custom-ccp/build
    files:
      - '**/*'
  cache:
    paths:
      - custom-ccp/node_modules/**/*
